name: Python application with Make and Flask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install dependencies using Makefile
    - name: Install dependencies
      run: |
        make install  # This should set up your virtual environment and install dependencies

    # Step 4: Run the application using Makefile
    - name: Run Flask app with Makefile
      run: |
        make run &  # Run the server in the background
        sleep 10  # Allow time for the server to start

    # Step 5: Check if the server is running
    - name: Test server is running
      run: |
        curl -f http://localhost:3000 || exit 1  # Verify that the server responds
